lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_identity_field: 'email' # Any of the properties/getters in the user object
    user_id_claim: 'email' # The fieldname used in the JWT payload for the user identity
    token_ttl: 9999999 # in seconds, default is 3600